locale                   : "en-US"
title                    : "Raymond Lesiyon"
title_separator          : "-"
name                     : &name "Raymond Lesiyon"
description              : &description "Passionate in utilizing ML methods, and employing FAIR principles of data sharing/management to answer biological question."

author:
  # Biographic information
  avatar           : "avatar.png"
  name             : "Raymond Lesiyon"
  pronouns         : "he/his"  
  bio              : "Computational Biologist"
  location         : "Aurora, Colorado"
  employer         : "University of Colorado Anschutz Campus"
  email            : "raymondlesiyon@gmail.com" 

lsi: false
safe: true
source: [.]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
