locale                   : "en-US"
title                    : "Raymond Lesiyon Informatic Professional|Computational Biologist"
title_separator          : "-"
name                     : &name "Raymond Lesiyon"
description              : &description "I am passionate in leveraging computational methods to advance healthcare through biological data analysis. With this, I am looking to develop expertise in Machine Learning, Deep Learning, and Data management."

author:
  # Biographic information
  avatar           : "avatar.png"
  name             : "Raymond Lesiyon"
  pronouns         : "he/his"  
  bio              : "Computational Biologist"
  location         : "Aurora, Colorado"
  employer         : "University of Colorado Anschutz Campus"
  email            : "raymondlesiyon@gmail.com" 

lsi: false
safe: true
source: [.]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
