title: Raymond Lesiyon  # You can add your name here

logo: avatar.jpg # Use a relative path to logo image 

description: Computational Scientist with huge interest on method application to answer question with biological data.

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: youremail@gmail.com # Allow visitors to contact you
